-- LifePilot Gameplay expansion
-- Production migration applied to project rhafdhwixhqxufylavag.
-- Includes XP/levels, LifeCoins, sessions, missions, challenges, achievements and LifeShop vouchers.

alter table public.profiles add column if not exists xp integer not null default 0;
alter table public.profiles add column if not exists level integer not null default 1;
alter table public.profiles add column if not exists lifecoins integer not null default 0;
alter table public.profiles add column if not exists current_streak integer not null default 0;
alter table public.profiles add column if not exists best_streak integer not null default 0;
alter table public.profiles add column if not exists last_activity_date date;

create table if not exists public.life_sessions (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, goal_id uuid references public.goals(id) on delete set null, title text not null, description text not null default '', session_type text not null default 'focus', starts_at timestamptz not null, ends_at timestamptz not null, status text not null default 'scheduled' check(status in ('scheduled','completed','skipped','cancelled')), xp_reward integer not null default 25, coin_reward integer not null default 10, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.life_xp_ledger (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, source_type text not null, source_id uuid not null, xp integer not null default 0, coins integer not null default 0, created_at timestamptz not null default now(), unique(user_id,source_type,source_id));
create table if not exists public.life_achievements (id uuid primary key default gen_random_uuid(), code text unique not null, title text not null, description text not null, icon text not null default '🏆', xp_reward integer not null default 0, coin_reward integer not null default 0, created_at timestamptz not null default now());
create table if not exists public.life_user_achievements (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, achievement_id uuid not null references public.life_achievements(id) on delete cascade, unlocked_at timestamptz not null default now(), unique(user_id,achievement_id));
create table if not exists public.life_challenges (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, title text not null, description text not null default '', target integer not null, progress integer not null default 0, xp_reward integer not null default 100, coin_reward integer not null default 50, starts_on date not null, ends_on date not null, completed_at timestamptz);
create table if not exists public.life_missions (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, mission_date date not null, title text not null, description text not null default '', target integer not null default 1, progress integer not null default 0, xp_reward integer not null default 30, coin_reward integer not null default 15, completed_at timestamptz, created_at timestamptz not null default now(), unique(user_id,mission_date,title));
create table if not exists public.life_shop_items (id uuid primary key default gen_random_uuid(), name text not null, description text not null default '', category text not null default 'clothing', coins_cost integer not null, discount_percent integer not null default 0, code_prefix text not null default 'LIFE', active boolean not null default true, created_at timestamptz not null default now());
create table if not exists public.life_shop_redemptions (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, item_id uuid not null references public.life_shop_items(id), coins_spent integer not null, voucher_code text unique not null, discount_percent integer not null, redeemed_at timestamptz not null default now());

-- See the repository commit that introduced the complete RLS policies and reward functions for the canonical production version.
