import React,{useEffect,useState} from 'react';
import {ArrowRight,Check,LoaderCircle} from 'lucide-react';
import {supabase} from './lib/supabase';

export default function AdaptiveQuiz({goal,nav,sessionId}){
 const [questions,setQuestions]=useState([]),[answers,setAnswers]=useState({}),[index,setIndex]=useState(0),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[result,setResult]=useState(null),[error,setError]=useState('');
 useEffect(()=>{let alive=true;(async()=>{if(!sessionId||!goal?.id){setError('Sessione Focus non valida.');setLoading(false);return}const{data,error:e}=await supabase.rpc('get_adaptive_quiz',{p_session_id:sessionId,p_goal_id:goal.id});if(!alive)return;if(e)setError(e.message);else setQuestions(Array.isArray(data)?data:[]);setLoading(false)})();return()=>{alive=false}},[sessionId,goal?.id]);
 const submit=async()=>{setBusy(true);setError('');try{const payload=questions.map(q=>({question_id:q.id,answer:answers[q.id]}));const{data,error:e}=await supabase.rpc('submit_adaptive_quiz',{p_session_id:sessionId,p_goal_id:goal.id,p_answers:payload});if(e)throw e;if(data?.passed){const{error:ce}=await supabase.rpc('complete_life_session',{p_session_id:sessionId});if(ce)throw ce}setResult(data)}catch(e){setError(e.message||'Impossibile registrare il quiz.')}finally{setBusy(false)}};
 if(loading)return <Page title="Adaptive Quiz" subtitle="Adattamento della difficoltà in base alla tua mastery."><Panel><LoaderCircle className="spin"/> Caricamento quiz…</Panel></Page>;
 if(error&&!questions.length)return <Page title="Adaptive Quiz" subtitle="Il quiz richiede una sessione Focus valida."><Panel><div className="msg error">{error}</div><button className="primary" onClick={()=>nav('focus')}>Torna al Focus</button></Panel></Page>;
 if(result)return <Page title="Risultato" subtitle="Mastery, XP e reward sono stati registrati dal server."><Panel><h1>{result.score}/{result.total}</h1><h2>{result.passed?'Quiz superato ✓':'Quiz non superato'}</h2><p className="muted">{result.passed?'La mastery delle skill coinvolte è stata aggiornata.':'Riprova con un nuovo Focus per consolidare le skill.'}</p>{error&&<div className="msg error">{error}</div>}<button className="primary" onClick={()=>nav('gameplay')}>Vai a Gameplay <ArrowRight/></button></Panel></Page>;
 const q=questions[index];if(!q)return <Page title="Adaptive Quiz" subtitle="Nessuna domanda disponibile."><Panel><p className="muted">Il server non ha trovato domande compatibili con la tua mastery.</p><button className="primary" onClick={()=>nav('focus')}>Torna al Focus</button></Panel></Page>;
 return <Page title="Adaptive Quiz" subtitle={`Domanda ${index+1}/${questions.length} · difficoltà ${q.difficulty}`}><Panel><span className="eyebrow">{q.skill}</span><h2>{q.question}</h2>{q.options.map((option,k)=><button key={option} className="task-button" onClick={()=>setAnswers({...answers,[q.id]:k})}><span className="check">{answers[q.id]===k&&<Check/>}</span>{option}</button>)}<div className="quick-row">{index>0&&<button onClick={()=>setIndex(index-1)}>Indietro</button>}{index<questions.length-1?<button className="primary" disabled={answers[q.id]===undefined} onClick={()=>setIndex(index+1)}>Continua <ArrowRight/></button>:<button className="primary" disabled={questions.some(x=>answers[x.id]===undefined)||busy} onClick={submit}>{busy?'Salvataggio…':'Concludi quiz'} <Check/></button>}</div>{error&&<div className="msg error">{error}</div>}</Panel></Page>
}
function Page({title,subtitle,children}){return <div className="page"><div className="page-head"><div><span className="eyebrow">LIFEPILOT</span><h1>{title}</h1><p>{subtitle}</p></div></div>{children}</div>}
function Panel({children}){return <section className="panel">{children}</section>}
