import { supabase } from './lib/supabase';

const SELECTORS={page:'.lp-main .page',primary:'.primary',timer:'.timer',focusPresets:'.focus-presets',panel:'.lp-main .panel'};
let cleanup=[];
let domObserver=null;
let applyTimer=null;
let lastPageKey='';

function on(el,event,handler,options){el?.addEventListener(event,handler,options);if(el)cleanup.push(()=>el.removeEventListener(event,handler,options));}
function addStyle(){if(document.getElementById('lp-functional-polish-style'))return;const style=document.createElement('style');style.id='lp-functional-polish-style';style.textContent=`
.lp-fp-toolbar{display:flex;align-items:center;justify-content:space-between;gap:12px;flex-wrap:wrap;margin-bottom:14px}.lp-fp-status{display:inline-flex;align-items:center;gap:7px;padding:7px 10px;border-radius:999px;background:var(--soft,#eef2ff);color:var(--primary,#6c5ce7);font-size:12px;font-weight:800}.lp-fp-status-dot{width:7px;height:7px;border-radius:50%;background:currentColor}.lp-fp-hint{font-size:12px;color:var(--muted,#667085)}.lp-fp-action{border:1px solid var(--border);background:var(--card);color:var(--text);border-radius:11px;padding:9px 12px;font-weight:800}.lp-fp-action:hover{border-color:var(--primary);color:var(--primary)}.lp-fp-count{display:inline-flex;min-width:22px;height:22px;padding:0 6px;align-items:center;justify-content:center;border-radius:999px;background:var(--soft);color:var(--primary);font-size:11px;font-weight:900}.lp-fp-unsaved{font-size:12px;color:#b45309;font-weight:800;margin-top:8px}.lp-fp-saved{font-size:12px;color:#15803d;font-weight:800;margin-top:8px}.lp-fp-bar-label{display:flex;justify-content:space-between;gap:8px;align-items:center;font-size:11px;color:var(--muted);margin-top:4px}@media(max-width:800px){.lp-fp-toolbar{align-items:flex-start}.lp-fp-hint{width:100%}.lp-fp-action{min-height:42px}}
`;document.head.appendChild(style)}
function currentPageTitle(){return document.querySelector('.lp-main .page h1')?.textContent?.trim()||''}
function enhanceFocus(){const page=document.querySelector(SELECTORS.page);if(!page||currentPageTitle()!=='Focus')return;const timer=page.querySelector(SELECTORS.timer),presets=page.querySelector(SELECTORS.focusPresets),primary=[...page.querySelectorAll(SELECTORS.primary)].find(b=>/focus|pausa|salva/i.test(b.textContent||''));if(!timer||!primary)return;if(!page.querySelector('[data-lp-fp-focus-toolbar]')){const toolbar=document.createElement('div');toolbar.className='lp-fp-toolbar';toolbar.dataset.lpFpFocusToolbar='1';toolbar.innerHTML='<span class="lp-fp-status"><span class="lp-fp-status-dot"></span><span data-lp-focus-status>Pronto</span></span><span class="lp-fp-hint">Scorciatoia: <strong>Spazio</strong> avvia / mette in pausa</span>';timer.parentElement?.insertBefore(toolbar,timer)}const status=page.querySelector('[data-lp-focus-status]');const update=()=>{const text=primary.textContent||'';if(/pausa/i.test(text)){if(status)status.textContent='Sessione in corso';document.title=`${timer.textContent?.trim()||'Focus'} · LifePilot`}else if(/inizia/i.test(text)){if(status)status.textContent='Pronto';document.title='Focus · LifePilot'}else if(/salva/i.test(text)){if(status)status.textContent='Sessione completata';document.title='Sessione completata · LifePilot'}};const observer=new MutationObserver(update);observer.observe(primary,{childList:true,subtree:true,characterData:true});observer.observe(timer,{childList:true,subtree:true,characterData:true});cleanup.push(()=>observer.disconnect());if(presets){presets.querySelectorAll('button').forEach(button=>{const value=button.classList.contains('selected')?'true':'false';if(button.getAttribute('aria-pressed')!==value)button.setAttribute('aria-pressed',value);on(button,'click',()=>{presets.querySelectorAll('button').forEach(b=>{const next=b===button?'true':'false';if(b.getAttribute('aria-pressed')!==next)b.setAttribute('aria-pressed',next)})})})}on(document,'keydown',event=>{if(event.code!=='Space'||event.repeat)return;const tag=document.activeElement?.tagName;if(tag==='INPUT'||tag==='TEXTAREA'||tag==='SELECT'||document.activeElement?.isContentEditable)return;event.preventDefault();primary.click()});update()}
function enhanceProgress(){const page=document.querySelector(SELECTORS.page);if(!page||currentPageTitle()!=='Progressi')return;const bars=page.querySelectorAll('.bars > div');if(!bars.length)return;let max=1;const values=[];bars.forEach(item=>{const bar=item.querySelector('.bar');if(!bar)return;const stored=bar.dataset.lpFpValue;const value=stored!==undefined?Number(stored):Math.max(0,Math.round((parseFloat(bar.style.height||'0')||0)/18));bar.dataset.lpFpValue=String(value);values.push(value);max=Math.max(max,value)});bars.forEach((item,index)=>{const bar=item.querySelector('.bar');if(!bar)return;const value=values[index];const height=Math.max(8,Math.round((value/max)*100));if(bar.style.height!==`${height}%`)bar.style.height=`${height}%`;bar.setAttribute('role','img');bar.setAttribute('aria-label',`${value} task completati`);if(!item.querySelector('.lp-fp-bar-label')){const label=document.createElement('div');label.className='lp-fp-bar-label';label.innerHTML=`<span>${value} completati</span>`;item.appendChild(label)}})}
async function markAllNotificationsRead(page){if(!page.querySelector('.notice:not(.read)'))return;const {data:{user}}=await supabase.auth.getUser();if(!user)return;const {error}=await supabase.from('notifications').update({read_at:new Date().toISOString()}).eq('user_id',user.id).is('read_at',null);if(error)throw error;window.location.reload()}
function enhanceNotifications(){const page=document.querySelector(SELECTORS.page);if(!page||currentPageTitle()!=='Notifiche')return;const notices=[...page.querySelectorAll('.notice')];if(!notices.length||page.querySelector('[data-lp-fp-notification-toolbar]'))return;const panel=page.querySelector(SELECTORS.panel);if(!panel)return;const unread=notices.filter(n=>!n.classList.contains('read')).length;const toolbar=document.createElement('div');toolbar.className='lp-fp-toolbar';toolbar.dataset.lpFpNotificationToolbar='1';toolbar.innerHTML=`<span class="lp-fp-status"><span class="lp-fp-count">${unread}</span> ${unread===1?'notifica da leggere':'notifiche da leggere'}</span>`;if(unread){const button=document.createElement('button');button.className='lp-fp-action';button.dataset.lpFpNotificationAction='1';button.textContent='Segna tutte come lette';on(button,'click',async()=>{button.disabled=true;button.textContent='Aggiornamento…';try{await markAllNotificationsRead(page)}catch(error){button.disabled=false;button.textContent='Riprova';console.error(error)}});toolbar.appendChild(button)}panel.insertBefore(toolbar,panel.firstChild)}
function enhanceProfile(){const page=document.querySelector(SELECTORS.page);if(!page||currentPageTitle()!=='Profilo')return;const inputs=[...page.querySelectorAll('input')],nickname=inputs.find(i=>i.type==='text')||inputs[0],save=[...page.querySelectorAll('.primary')].find(b=>/salva modifiche/i.test(b.textContent||''));if(!nickname||!save||page.querySelector('[data-lp-fp-profile-state]'))return;const state=document.createElement('div');state.dataset.lpFpProfileState='1';state.className='lp-fp-saved';state.textContent='Nessuna modifica da salvare.';nickname.parentElement?.appendChild(state);const original=nickname.value;const update=()=>{const valid=nickname.value.trim().length>=2,dirty=nickname.value!==original;save.disabled=!valid||!dirty;state.className=dirty?'lp-fp-unsaved':'lp-fp-saved';state.textContent=dirty?(valid?'Modifiche non ancora salvate.':'Inserisci almeno 2 caratteri.'):'Nessuna modifica da salvare.'};on(nickname,'input',update);update()}
function apply(){addStyle();cleanup.forEach(fn=>fn());cleanup=[];const page=document.querySelector(SELECTORS.page);const key=page?`${currentPageTitle()}|${page.querySelector('[data-lp-fp-focus-toolbar],[data-lp-fp-notification-toolbar],[data-lp-fp-profile-state]')?'enhanced':'base'}`:'';if(key===lastPageKey&&page)return;lastPageKey=key;enhanceFocus();enhanceProgress();enhanceNotifications();enhanceProfile()}
function scheduleApply(){clearTimeout(applyTimer);applyTimer=setTimeout(apply,60)}
function start(){apply();domObserver=new MutationObserver(scheduleApply);domObserver.observe(document.body,{childList:true,subtree:true})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else start();
export function stopFunctionalPolish(){clearTimeout(applyTimer);cleanup.forEach(fn=>fn());cleanup=[];domObserver?.disconnect();domObserver=null;lastPageKey=''}
