import { supabase } from './lib/supabase';
import './game-hud.css';
const AVATARS={nova:'🧑‍🚀',fox:'🦊',wolf:'🐺',dragon:'🐉',bot:'🤖',mage:'🧙',ninja:'🥷',knight:'🛡️'};
const labels={nova:'Nova',fox:'Fox',wolf:'Wolf',dragon:'Dragon',bot:'Bot',mage:'Mage',ninja:'Ninja',knight:'Knight'};
let user=null,profile=null,progression=null;
const esc=(s='')=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const avatar=()=>AVATARS[profile?.avatar_key]||AVATARS.nova;
async function refresh(){if(!user)return;const[{data:p},{data:pr}]=await Promise.all([supabase.from('profiles').select('nickname,avatar_key,level,xp,lifecoins').eq('id',user.id).maybeSingle(),supabase.rpc('get_progression_summary')]);profile=p||profile;progression=pr||progression;render()}
function nav(route){window.dispatchEvent(new CustomEvent('lifepilot:navigate',{detail:route}))}
function render(){const top=document.querySelector('.lp-top'),side=document.querySelector('.lp-side');if(!top||!side||!profile)return;const level=progression?.level??profile.level??1,xp=progression?.xp_into_level??0,next=progression?.xp_for_next_level??250,coins=progression?.lifecoins??profile.lifecoins??0,title=progression?.title||'Novice',pct=Math.min(100,Math.round(xp/Math.max(1,next)*100));let hud=top.querySelector('.game-hud');if(!hud){hud=document.createElement('div');hud.className='game-hud';top.insertBefore(hud,top.querySelector('.avatar'))}hud.innerHTML=`<button class="hud-level" aria-label="Profilo"><span class="hud-badge">LV ${level}</span><span class="hud-title">${esc(title)}</span><span class="hud-xp"><i style="width:${pct}%"></i></span><small>${xp} / ${next} XP</small></button><button class="hud-coins" aria-label="LifeCoins">🪙 <strong>${coins}</strong><small>LifeCoins</small></button>`;hud.children[0].onclick=()=>nav('profile');hud.children[1].onclick=()=>nav('shop');const brand=top.querySelector('.lp-brand');if(brand)brand.textContent='✦ LIFE // PILOT';const av=top.querySelector('.avatar');if(av){av.textContent=avatar();av.title=`${labels[profile.avatar_key]||'Nova'} · Modifica avatar`;av.onclick=openAvatarForge}let card=side.querySelector('.sidebar-player-card');if(!card){card=document.createElement('button');card.className='sidebar-player-card';card.onclick=()=>nav('profile');side.insertBefore(card,side.firstChild)}card.innerHTML=`<span class="sidebar-avatar">${avatar()}</span><span><b>${esc(profile.nickname||'Pilota')}</b><small>LV ${level} · ${esc(title)}</small></span><em>›</em>`}
function openAvatarForge(){let modal=document.querySelector('.avatar-forge');if(modal)return;modal=document.createElement('div');modal.className='avatar-forge';modal.innerHTML=`<div class="avatar-forge-card"><button class="avatar-close" aria-label="Chiudi">×</button><span class="eyebrow">CHARACTER FORGE</span><h2>Scegli il tuo avatar</h2><p class="muted">Cosmetico: non modifica XP, LifeCoins o progressione.</p><div class="avatar-grid">${Object.entries(AVATARS).map(([k,v])=>`<button data-avatar="${k}"><span>${v}</span><small>${labels[k]}</small></button>`).join('')}</div></div>`;document.body.appendChild(modal);modal.querySelector('.avatar-close').onclick=()=>modal.remove();modal.onclick=e=>{if(e.target===modal)modal.remove()};modal.querySelectorAll('[data-avatar]').forEach(b=>b.onclick=async()=>{const key=b.dataset.avatar;const{error}=await supabase.from('profiles').update({avatar_key:key}).eq('id',user.id);if(error)return;profile.avatar_key=key;modal.remove();render()})}
function hookNav(){window.addEventListener('lifepilot:navigate',e=>{const target=String(e.detail||'').toLowerCase();const b=[...document.querySelectorAll('.lp-side .nav button')].find(x=>x.textContent.trim().toLowerCase().startsWith(target));if(b)b.click()})}
async function boot(){const{data}=await supabase.auth.getSession();user=data.session?.user||null;if(user)await refresh();supabase.auth.onAuthStateChange((_e,s)=>{user=s?.user||null;if(user)refresh()});hookNav();new MutationObserver(render).observe(document.body,{childList:true,subtree:true})}boot();
