import { supabase } from './lib/supabase'

let userId = null
let overlay = null

const esc = (v) => String(v ?? '').replace(/[&<>'"]/g, (c) => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))
const today = () => { const d = new Date(); return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}` }

function injectStyles(){
 if(document.getElementById('lp-game-ui-style')) return
 const s=document.createElement('style'); s.id='lp-game-ui-style'; s.textContent=`
 .lp-gameplay-launch{width:100%;margin-top:10px!important;display:flex!important;align-items:center!important;justify-content:flex-start!important;gap:10px!important;border:1px solid var(--border)!important;background:var(--surface-soft)!important;color:var(--text)!important;border-radius:12px!important;font-weight:800!important}
 .lp-gameplay-home{margin:16px 0;padding:18px;border:1px solid var(--border);border-radius:18px;background:var(--surface-soft);display:flex;align-items:center;justify-content:space-between;gap:14px}.lp-gameplay-home h3{margin:0 0 5px}.lp-gameplay-home p{margin:0;color:var(--text-soft)}
 .lp-game-ui-overlay{position:fixed;inset:0;z-index:10060;background:rgba(8,11,18,.62);backdrop-filter:blur(7px);display:none;align-items:center;justify-content:center;padding:12px}.lp-game-ui-overlay.open{display:flex}.lp-game-ui-box{width:min(920px,100%);max-height:92vh;overflow:auto;background:var(--surface);color:var(--text);border:1px solid var(--border);border-radius:24px;padding:20px;box-shadow:0 30px 90px rgba(0,0,0,.35)}
 .lp-game-ui-head{display:flex;justify-content:space-between;gap:14px;align-items:flex-start}.lp-game-ui-head h2{margin:3px 0}.lp-game-ui-head p{margin:0;color:var(--text-soft)}.lp-game-ui-close{width:42px;height:42px;border:0;border-radius:12px;background:var(--surface-soft);color:var(--text);font-size:24px}.lp-game-ui-tabs{display:flex;gap:8px;overflow:auto;margin:16px 0}.lp-game-ui-tabs button,.lp-game-ui-btn{border:1px solid var(--border);background:var(--surface-soft);color:var(--text);border-radius:11px;padding:10px 13px;font-weight:800}.lp-game-ui-tabs button.active,.lp-game-ui-primary{background:var(--primary);color:#fff;border-color:var(--primary)}
 .lp-game-ui-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:10px}.lp-game-ui-card{border:1px solid var(--border);border-radius:16px;background:var(--surface-soft);padding:15px}.lp-game-ui-card span{display:block;font-size:10px;color:var(--text-muted);font-weight:900;text-transform:uppercase}.lp-game-ui-card b{display:block;font-size:24px;margin-top:4px}.lp-game-ui-section{margin-top:12px;border:1px solid var(--border);border-radius:17px;padding:16px}.lp-game-ui-row{display:flex;justify-content:space-between;align-items:center;gap:12px;padding:12px 0;border-bottom:1px solid var(--border)}.lp-game-ui-row:last-child{border-bottom:0}.lp-game-ui-row small{display:block;color:var(--text-muted);margin-top:3px}.lp-game-ui-form{display:grid;grid-template-columns:2fr 1fr 1fr 1fr;gap:10px}.lp-game-ui-form label{display:flex;flex-direction:column;gap:5px;font-size:12px;font-weight:800;color:var(--text-soft)}.lp-game-ui-form input,.lp-game-ui-form select{padding:11px;border:1px solid var(--border);border-radius:10px;background:var(--surface);color:var(--text);font:inherit}.lp-game-ui-full{grid-column:1/-1}.lp-game-ui-progress{height:8px;background:var(--surface-soft);border-radius:99px;overflow:hidden;margin-top:8px}.lp-game-ui-progress i{display:block;height:100%;background:var(--primary)}.lp-game-ui-muted{color:var(--text-soft)}
 @media(max-width:760px){.lp-game-ui-grid{grid-template-columns:repeat(2,1fr)}.lp-game-ui-form{grid-template-columns:1fr 1fr}.lp-game-ui-full{grid-column:1/-1}.lp-gameplay-home{align-items:flex-start;flex-direction:column}}
 `; document.head.appendChild(s)
}

async function load(){
 const p=await supabase.from('profiles').select('xp,level,lifecoins,current_streak,best_streak').eq('id',userId).maybeSingle()
 const g=await supabase.from('goals').select('id,title,category').eq('user_id',userId).order('created_at',{ascending:false})
 const s=await supabase.from('life_sessions').select('*').eq('user_id',userId).order('starts_at')
 return {profile:p.data||{},goals:g.data||[],sessions:s.data||[],error:p.error||g.error||s.error}
}

function buildOverlay(){
 if(overlay) return
 overlay=document.createElement('div'); overlay.className='lp-game-ui-overlay'; overlay.innerHTML=`<div class="lp-game-ui-box"><div class="lp-game-ui-head"><div><span class="eyebrow">LIFEPILOT GAMEPLAY</span><h2>La tua progressione</h2><p>Pianifica → completa → guadagna XP e LifeCoins.</p></div><button class="lp-game-ui-close" aria-label="Chiudi">×</button></div><div class="lp-game-ui-tabs"><button data-tab="progress" class="active">Progressione</button><button data-tab="missions">Missioni</button><button data-tab="sessions">Sessioni</button><button data-tab="shop">LifeShop</button><button data-tab="coach">AI Coach</button></div><div class="lp-game-ui-body"></div></div>`
 document.body.appendChild(overlay)
 overlay.querySelector('.lp-game-ui-close').onclick=()=>overlay.classList.remove('open')
 overlay.addEventListener('click',(e)=>{if(e.target===overlay)overlay.classList.remove('open');const b=e.target.closest('[data-tab]');if(b)render(b.dataset.tab)})
}

async function render(tab='progress'){
 const body=overlay.querySelector('.lp-game-ui-body'); body.innerHTML='<p class="lp-game-ui-muted">Caricamento…</p>'
 const d=await load(); overlay.querySelectorAll('[data-tab]').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab))
 if(d.error){body.innerHTML=`<div class="lp-game-ui-section"><b>Gameplay in preparazione</b><p class="lp-game-ui-muted">Il modulo è attivo, ma il database non ha ancora restituito tutti i dati necessari. Aggiorna la pagina dopo il deployment.</p></div>`;return}
 if(tab==='progress') progress(body,d); if(tab==='missions') missions(body,d); if(tab==='sessions') sessions(body,d); if(tab==='shop') shop(body,d); if(tab==='coach') coach(body,d)
}

function progress(b,d){const p=d.profile||{},x=Number(p.xp||0),l=Number(p.level||1),coins=Number(p.lifecoins||0),streak=Number(p.current_streak||0),pct=Math.max(0,Math.min(100,Math.round(((x-(l-1)*250)/250)*100)));b.innerHTML=`<div class="lp-game-ui-grid"><div class="lp-game-ui-card"><span>Livello</span><b>${l}</b><div class="lp-game-ui-progress"><i style="width:${pct}%"></i></div></div><div class="lp-game-ui-card"><span>XP</span><b>${x}</b></div><div class="lp-game-ui-card"><span>LifeCoins</span><b>🪙 ${coins}</b></div><div class="lp-game-ui-card"><span>Streak</span><b>🔥 ${streak}</b></div></div><div class="lp-game-ui-section"><h3>🏆 Achievement</h3><div class="lp-game-ui-row"><div><b>🎯 Prima sessione</b><small>Completa la prima sessione programmata.</small></div><span>+50 XP</span></div><div class="lp-game-ui-row"><div><b>🔥 Settimana di costanza</b><small>7 giorni di streak.</small></div><span>+100 XP</span></div><div class="lp-game-ui-row"><div><b>🧠 Deep Worker</b><small>10 sessioni completate.</small></div><span>+150 XP</span></div></div>`}
function missions(b,d){const done=d.sessions.filter(s=>s.status==='completed').length;b.innerHTML=`<div class="lp-game-ui-section"><h3>🎯 Missioni di oggi</h3><div class="lp-game-ui-row"><div><b>Completa 3 attività</b><small>Porta avanti il tuo percorso.</small></div><span>+40 XP · +20 🪙</span></div><div class="lp-game-ui-row"><div><b>Completa una sessione Focus</b><small>Almeno una sessione.</small></div><span>+35 XP · +15 🪙</span></div><div class="lp-game-ui-row"><div><b>Avanza sul tuo obiettivo</b><small>Completa una sessione collegata.</small></div><span>+50 XP · +25 🪙</span></div></div><div class="lp-game-ui-section"><h3>⚔️ Challenge settimanale</h3><p>Sessioni completate: <b>${Math.min(done,5)}/5</b></p><div class="lp-game-ui-progress"><i style="width:${Math.min(100,done*20)}%"></i></div><p>Ricompensa: +150 XP · +75 LifeCoins</p></div>`}
function sessions(b,d){const up=d.sessions.filter(s=>s.status==='scheduled').slice(0,10);b.innerHTML=`<div class="lp-game-ui-section"><h3>📅 Programma una sessione</h3><form id="lp-game-session-form" class="lp-game-ui-form"><label class="lp-game-ui-full">Titolo<input name="title" placeholder="Studio capitolo 4" required></label><label>Obiettivo<select name="goal"><option value="">Nessuno</option>${d.goals.map(g=>`<option value="${g.id}">${esc(g.title)}</option>`).join('')}</select></label><label>Data<input name="date" type="date" value="${today()}" required></label><label>Ora<input name="time" type="time" value="18:00" required></label><label>Minuti<input name="minutes" type="number" min="5" max="240" value="30" required></label><button class="lp-game-ui-btn lp-game-ui-primary lp-game-ui-full">Programma</button></form></div><div class="lp-game-ui-section"><h3>Prossime sessioni</h3>${up.map(s=>`<div class="lp-game-ui-row"><div><b>${esc(s.title)}</b><small>${new Date(s.starts_at).toLocaleString('it-IT',{weekday:'short',day:'numeric',month:'short',hour:'2-digit',minute:'2-digit'})}</small></div></div>`).join('')||'<p class="lp-game-ui-muted">Nessuna sessione programmata.</p>'}</div>`;b.querySelector('#lp-game-session-form').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.currentTarget),mins=Number(f.get('minutes')),start=new Date(`${f.get('date')}T${f.get('time')}`),end=new Date(start.getTime()+mins*60000);const r=await supabase.from('life_sessions').insert({user_id:userId,goal_id:f.get('goal')||null,title:String(f.get('title')).trim(),session_type:'goal',starts_at:start.toISOString(),ends_at:end.toISOString(),xp_reward:25+Math.min(50,Math.floor(mins/10)*5),coin_reward:10+Math.min(30,Math.floor(mins/15)*5)});if(r.error)alert(r.error.message);else render('sessions')}}
function shop(b,d){b.innerHTML=`<div class="lp-game-ui-section"><h3>🛍️ LifeShop</h3><p class="lp-game-ui-muted">Usa i LifeCoins per ottenere voucher e sconti sull'abbigliamento.</p><div class="lp-game-ui-row"><div><b>Voucher abbigliamento</b><small>500 LifeCoins → 10% di sconto</small></div><span>🪙 500</span></div><div class="lp-game-ui-row"><div><b>Voucher abbigliamento Plus</b><small>1.000 LifeCoins → 20% di sconto</small></div><span>🪙 1.000</span></div></div>`}
function coach(b,d){b.innerHTML=`<div class="lp-game-ui-section"><h3>🤖 Game Master Gemini</h3><p class="lp-game-ui-muted">Genera un percorso e programma le sessioni nel Calendario.</p><form id="lp-game-coach-form" class="lp-game-ui-form"><label class="lp-game-ui-full">Obiettivo<select name="goal">${d.goals.map(g=>`<option value="${g.id}">${esc(g.title)}</option>`).join('')}</select></label><label>Durata (giorni)<input name="days" type="number" min="1" max="365" value="30"></label><label>Minuti/giorno<input name="minutes" type="number" min="5" max="240" value="30"></label><label>Ora<input name="time" type="time" value="18:00"></label><button class="lp-game-ui-btn lp-game-ui-primary lp-game-ui-full">Genera</button></form><div id="lp-game-coach-result"></div></div>`;b.querySelector('#lp-game-coach-form').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.currentTarget),g=d.goals.find(x=>x.id===f.get('goal')),out=b.querySelector('#lp-game-coach-result');if(!g){out.innerHTML='<p>Nessun obiettivo disponibile.</p>';return}out.innerHTML='<p class="lp-game-ui-muted">Gemini sta generando il percorso…</p>';const {data:r,error}=await supabase.functions.invoke('generate-plan',{body:{title:g.title,category:g.category,days:Number(f.get('days')),dailyMinutes:Number(f.get('minutes'))}});if(error||!Array.isArray(r?.plan)){out.innerHTML=`<p>Errore: ${esc(error?.message||r?.error||'generazione non riuscita')}</p>`;return}const tm=String(f.get('time')),rows=r.plan.map((x,i)=>{const dt=new Date();dt.setDate(dt.getDate()+Math.max(1,Number(x.day||i+1))-1);const [h,m]=tm.split(':').map(Number);dt.setHours(h||18,m||0,0,0);const en=new Date(dt.getTime()+Number(x.minutes||f.get('minutes'))*60000);return {user_id:userId,goal_id:g.id,title:String(x.title||`Sessione ${i+1}`),description:String(x.milestone||''),session_type:'goal',starts_at:dt.toISOString(),ends_at:en.toISOString(),xp_reward:30,coin_reward:15}});const ins=await supabase.from('life_sessions').insert(rows);out.innerHTML=ins.error?`<p>Errore: ${esc(ins.error.message)}</p>`:`<p>✓ ${rows.length} sessioni inserite nel Calendario.</p>`}}

function openGameplay(){injectStyles();buildOverlay();overlay.classList.add('open');render('progress')}

function addLauncher(){
 document.querySelectorAll('.lp-side .nav').forEach(nav=>{if(nav.querySelector('[data-lp-gameplay-launch]'))return;const b=document.createElement('button');b.type='button';b.className='lp-gameplay-launch';b.dataset.lpGameplayLaunch='1';b.innerHTML='🎮<span>Gameplay</span>';b.onclick=openGameplay;nav.appendChild(b)})
 const main=document.querySelector('.lp-main');if(main&&!main.querySelector('[data-lp-gameplay-home]')){const c=document.createElement('div');c.className='lp-gameplay-home';c.dataset.lpGameplayHome='1';c.innerHTML='<div><h3>🎮 Gameplay</h3><p>XP, livelli, missioni, sessioni, LifeCoins e AI Coach.</p></div><button type="button" class="lp-game-ui-btn lp-game-ui-primary">Apri Gameplay</button>';c.querySelector('button').onclick=openGameplay;main.prepend(c)}
}

function start(){injectStyles();addLauncher();const observer=new MutationObserver(addLauncher);observer.observe(document.body,{subtree:true,childList:true});}

supabase.auth.onAuthStateChange((_e,s)=>{userId=s?.user?.id||null;if(userId)start()})
supabase.auth.getSession().then(({data})=>{userId=data.session?.user?.id||null;if(userId)start()})
