import React,{useEffect,useMemo,useState} from 'react';
import {supabase} from './lib/supabase';
import {Activity,ArrowRight,BarChart3,Bell,CalendarDays,Check,ChevronLeft,ChevronRight,Clock,Flame,Home,LogOut,Menu,Plus,Sparkles,Target,Trophy,User,X,Zap} from 'lucide-react';
import './lifepilot-v2.css';

const today=()=>new Date().toISOString().slice(0,10);
const fmt=d=>new Date(`${d}T12:00:00`).toLocaleDateString('it-IT',{day:'numeric',month:'long'});
const pct=(a,b)=>b?Math.round((a/b)*100):0;

export default function LifePilotV2(){
 const [session,setSession]=useState(null),[boot,setBoot]=useState(true);
 useEffect(()=>{let live=true;supabase.auth.getSession().then(({data})=>{if(live){setSession(data.session);setBoot(false)}}).catch(()=>live&&setBoot(false));const {data:{subscription}}=supabase.auth.onAuthStateChange((_e,s)=>setSession(s));return()=>{live=false;subscription.unsubscribe()};},[]);
 if(boot)return <Splash/>; if(!session)return <Auth/>; return <App session={session}/>;
}
function Splash(){return <div className="lp-splash"><div className="lp-logo"><Sparkles/></div><h1>LifePilot</h1><p>Prepariamo il tuo percorso…</p></div>}
function Auth(){const [mode,setMode]=useState('login'),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[ok,setOk]=useState('');
 const submit=async e=>{e.preventDefault();setBusy(true);setError('');setOk('');try{if(password.length<6)throw Error('La password deve contenere almeno 6 caratteri.');if(mode==='signup'){const {data,error}=await supabase.auth.signUp({email:email.trim().toLowerCase(),password});if(error)throw error;if(!data.session)setOk('Account creato. Controlla la tua email per confermare l’account.')}else{const {error}=await supabase.auth.signInWithPassword({email:email.trim().toLowerCase(),password});if(error)throw error}}catch(e){setError(e.message||'Accesso non riuscito.')}finally{setBusy(false)}};
 return <div className="lp-auth"><div className="lp-auth-card"><div className="lp-logo small"><Sparkles/></div><span className="eyebrow">LIFEPILOT</span><h1>{mode==='login'?'Bentornato.':'Iniziamo.'}</h1><p className="muted">{mode==='login'?'Riprendi il tuo percorso un passo alla volta.':'Trasforma un obiettivo in un piano quotidiano.'}</p><form onSubmit={submit}><label>Email<input value={email} onChange={e=>setEmail(e.target.value)} type="email" autoComplete="email" required/></label><label>Password<input value={password} onChange={e=>setPassword(e.target.value)} type="password" autoComplete={mode==='login'?'current-password':'new-password'} required/></label>{error&&<div className="msg error">{error}</div>}{ok&&<div className="msg ok">{ok}</div>}<button className="primary wide" disabled={busy}>{busy?'Accesso in corso…':mode==='login'?'Accedi':'Crea account'}<ArrowRight size={18}/></button></form><button className="link-btn" onClick={()=>{setMode(mode==='login'?'signup':'login');setError('');setOk('')}}>{mode==='login'?'Non hai un account? Registrati':'Hai già un account? Accedi'}</button></div></div>}
function App({session}){const uid=session.user.id;const [profile,setProfile]=useState(null),[view,setView]=useState('home'),[goals,setGoals]=useState([]),[tasks,setTasks]=useState([]),[notes,setNotes]=useState([]),[loading,setLoading]=useState(true),[drawer,setDrawer]=useState(false),[unread,setUnread]=useState(0);
 const load=async()=>{setLoading(true);const [{data:p},{data:g},{data:t},{data:n}]=await Promise.all([supabase.from('profiles').select('*').eq('id',uid).maybeSingle(),supabase.from('goals').select('*').eq('user_id',uid).order('created_at',{ascending:false}),supabase.from('goal_tasks').select('*').eq('user_id',uid).order('task_date'),supabase.from('notifications').select('*').eq('user_id',uid).order('created_at',{ascending:false}).limit(50)]);setProfile(p);setGoals(g||[]);setTasks(t||[]);setNotes(n||[]);setUnread((n||[]).filter(x=>!x.read_at).length);setLoading(false)};
 useEffect(()=>{load()},[uid]);
 useEffect(()=>{const ch=supabase.channel(`lp-${uid}`).on('postgres_changes',{event:'*',schema:'public',table:'goals',filter:`user_id=eq.${uid}`},load).on('postgres_changes',{event:'*',schema:'public',table:'goal_tasks',filter:`user_id=eq.${uid}`},load).on('postgres_changes',{event:'*',schema:'public',table:'notifications',filter:`user_id=eq.${uid}`},load).subscribe();return()=>supabase.removeChannel(ch)},[uid]);
 if(!profile)return <ProfileSetup uid={uid} onDone={load}/>;
 const nav=v=>{setView(v);setDrawer(false)}; const logout=()=>supabase.auth.signOut();
 return <div className="lp-app"><header className="lp-top"><button className="icon" onClick={()=>setDrawer(true)}><Menu/></button><button className="lp-brand" onClick={()=>nav('home')}><span><Sparkles/></span>LifePilot</button><div className="top-actions"><button className="icon bell" onClick={()=>nav('notifications')}><Bell/>{unread>0&&<b>{unread}</b>}</button><button className="avatar" onClick={()=>nav('profile')}>{(profile.nickname||'U')[0].toUpperCase()}</button></div></header><aside className="lp-side"><Nav view={view} nav={nav} unread={unread}/><button className="logout" onClick={logout}><LogOut/>Esci</button></aside>{drawer&&<div className="drawer-bg" onClick={()=>setDrawer(false)}><aside className="lp-drawer" onClick={e=>e.stopPropagation()}><div className="drawer-head"><button className="lp-brand"><span><Sparkles/></span>LifePilot</button><button className="icon" onClick={()=>setDrawer(false)}><X/></button></div><Nav view={view} nav={nav} unread={unread}/><button className="logout" onClick={logout}><LogOut/>Esci</button></aside></div>}<main className="lp-main">{loading?<Panel>Caricamento dati…</Panel>:view==='home'?<Home profile={profile} goals={goals} tasks={tasks} nav={nav}/>:view==='plan'?<Plan goals={goals} tasks={tasks} uid={uid} reload={load}/>:view==='goals'?<Goals goals={goals} tasks={tasks} uid={uid} reload={load}/>:view==='calendar'?<Calendar tasks={tasks} onToggle={toggleTask}/>:view==='focus'?<Focus goals={goals} uid={uid}/>:view==='progress'?<Progress goals={goals} tasks={tasks}/>:view==='notifications'?<Notifications items={notes} uid={uid} reload={load}/>:<Profile profile={profile} uid={uid} onDone={load}/>}</main></div>;
 async function toggleTask(id,done){await supabase.from('goal_tasks').update({completed:!done,completed_at:!done?new Date().toISOString():null}).eq('id',id).eq('user_id',uid);await load()}
}
function Nav({view,nav,unread}){return <nav className="nav">{[['home','Home',Home],['plan','Il mio piano',Sparkles],['goals','Obiettivi',Target],['calendar','Calendario',CalendarDays],['focus','Focus',Zap],['progress','Progressi',BarChart3],['notifications','Notifiche',Bell],['profile','Profilo',User]].map(([v,l,I])=><button className={view===v?'active':''} onClick={()=>nav(v)} key={v}><I/>{l}{v==='notifications'&&unread>0&&<em>{unread}</em>}</button>)}</nav>}
function ProfileSetup({uid,onDone}){const [name,setName]=useState(''),[birth,setBirth]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');const save=async e=>{e.preventDefault();setBusy(true);const {error}=await supabase.from('profiles').upsert({id:uid,nickname:name.trim(),birth_date:birth},{onConflict:'id'});if(error)setError(error.message);else onDone();setBusy(false)};return <div className="center"><div className="card setup"><div className="lp-logo small"><Sparkles/></div><span className="eyebrow">BENVENUTO</span><h1>Costruiamo il tuo LifePlan.</h1><p className="muted">Prima scegli come vuoi essere chiamato.</p><form onSubmit={save}><label>Nickname<input value={name} onChange={e=>setName(e.target.value)} required minLength={2}/></label><label>Data di nascita<input type="date" value={birth} onChange={e=>setBirth(e.target.value)} required/></label>{error&&<div className="msg error">{error}</div>}<button className="primary wide" disabled={busy}>{busy?'Salvataggio…':'Continua'}<ArrowRight/></button></form></div></div>}
function Home({profile,goals,tasks,nav}){const t=tasks.filter(x=>x.task_date===today()),done=t.filter(x=>x.completed).length,total=tasks.length,completed=tasks.filter(x=>x.completed).length;const goal=goals[0];return <div className="page"><div className="hero"><div><span className="eyebrow">{fmt(today())}</span><h1>Ciao, {profile.nickname}. 👋</h1><p>Oggi non devi cambiare la tua vita. Devi solo fare il prossimo passo.</p></div><button className="primary" onClick={()=>nav('plan')}>Apri il piano<ArrowRight/></button></div><div className="metric-grid"><Metric icon={<Check/>} label="Oggi" value={`${done}/${t.length||0}`} /><Metric icon={<Flame/>} label="Streak" value={`${Math.max(...goals.map(g=>g.streak||0),0)} giorni`}/><Metric icon={<Target/>} label="Obiettivi" value={goals.length}/><Metric icon={<BarChart3/>} label="Completati" value={total?`${pct(completed,total)}%`:'0%'}/></div>{goal?<Panel><div className="panel-head"><div><span className="eyebrow">OBIETTIVO PRINCIPALE</span><h2>{goal.title}</h2></div><Target/></div><ProgressBar value={goal.progress||0}/><div className="quick-row"><button onClick={()=>nav('goals')}>Gestisci obiettivi</button><button onClick={()=>nav('focus')}>Inizia focus</button></div></Panel>:<Empty title="Il tuo primo obiettivo" text="Descrivi ciò che vuoi raggiungere e LifePilot costruirà il percorso." action="Crea il piano" onClick={()=>nav('goals')}/>}<Panel><div className="panel-head"><div><span className="eyebrow">OGGI</span><h2>I prossimi passi</h2></div><CalendarDays/></div>{t.length?t.slice(0,5).map(x=><TaskRow key={x.id} task={x}/>):<p className="muted">Nessun task per oggi. Vai nel Piano per generarne uno.</p>}</Panel></div>}
function Plan({goals,tasks,uid,reload}){const [goalId,setGoalId]=useState(goals[0]?.id||''),[generating,setGenerating]=useState(false),[days,setDays]=useState(30),[minutes,setMinutes]=useState(20),[error,setError]=useState('');const goal=goals.find(g=>g.id===goalId);const mine=tasks.filter(t=>t.goal_id===goalId&&t.task_date>=today()).slice(0,10);const generate=async()=>{if(!goal)return;setGenerating(true);setError('');try{const {data,error}=await supabase.functions.invoke('generate-plan',{body:{title:goal.title,category:goal.category,days, dailyMinutes:minutes}});if(error)throw error;const items=data?.plan||[];const start=new Date();const rows=items.map((x,i)=>{const d=new Date(start);d.setDate(d.getDate()+Math.max(0,Number(x.day||i+1)-1));return {goal_id:goal.id,user_id:uid,task_date:d.toISOString().slice(0,10),title:String(x.title||`Azione ${i+1}`),priority:2}});if(rows.length){await supabase.from('goal_tasks').delete().eq('goal_id',goal.id).eq('user_id',uid);const {error:e}=await supabase.from('goal_tasks').insert(rows);if(e)throw e;}await supabase.from('goals').update({days,daily_minutes:minutes,plan:items}).eq('id',goal.id).eq('user_id',uid);await reload()}catch(e){setError(e.message||'Impossibile generare il piano.')}finally{setGenerating(false)}};return <div className="page"><Header title="Il mio piano" subtitle="Trasforma un obiettivo in azioni concrete."/><Panel><div className="form-grid"><label>Obiettivo<select value={goalId} onChange={e=>setGoalId(e.target.value)}>{goals.map(g=><option value={g.id} key={g.id}>{g.title}</option>)}</select></label><label>Durata (giorni)<input type="number" min="1" max="365" value={days} onChange={e=>setDays(Number(e.target.value))}/></label><label>Minuti al giorno<input type="number" min="5" max="240" value={minutes} onChange={e=>setMinutes(Number(e.target.value))}/></label></div>{error&&<div className="msg error">{error}</div>}<button className="primary" disabled={!goal||generating} onClick={generate}>{generating?'Creo il piano…':'Genera / rigenera il piano'}<Sparkles/></button></Panel><Panel><div className="panel-head"><h2>Prossimi passi</h2><span className="pill">{mine.length} task</span></div>{mine.length?mine.map(t=><TaskRow task={t} key={t.id}/>):<p className="muted">Genera il piano per creare automaticamente i task.</p>}</Panel></div>}
function Goals({goals,tasks,uid,reload}){const [open,setOpen]=useState(false),[title,setTitle]=useState(''),[cat,setCat]=useState('personale');const add=async e=>{e.preventDefault();if(!title.trim())return;await supabase.from('goals').insert({user_id:uid,title:title.trim(),category:cat,days:30,daily_minutes:20,priority:2,progress:0,streak:0});setTitle('');setOpen(false);reload()};const remove=async id=>{if(confirm('Eliminare questo obiettivo e i suoi task?')){await supabase.from('goals').delete().eq('id',id).eq('user_id',uid);reload()}};return <div className="page"><Header title="Obiettivi" subtitle="Pochi obiettivi, azioni quotidiane, progresso reale." action={<button className="primary" onClick={()=>setOpen(true)}><Plus/>Nuovo</button>}/>{open&&<Modal title="Nuovo obiettivo" close={()=>setOpen(false)}><form onSubmit={add}><label>Cosa vuoi raggiungere?<input autoFocus value={title} onChange={e=>setTitle(e.target.value)} placeholder="Es. trovare un nuovo lavoro" required/></label><label>Categoria<select value={cat} onChange={e=>setCat(e.target.value)}><option>carriera</option><option>salute</option><option>studio</option><option>finanze</option><option>personale</option></select></label><button className="primary wide">Crea obiettivo<ArrowRight/></button></form></Modal>}{goals.length?goals.map(g=>{const gt=tasks.filter(t=>t.goal_id===g.id),gd=gt.filter(t=>t.completed).length;return <Panel key={g.id}><div className="goal-line"><div><span className="eyebrow">{g.category}</span><h2>{g.title}</h2><p className="muted">{gd}/{gt.length} azioni completate · {g.days||30} giorni</p></div><button className="icon danger" onClick={()=>remove(g.id)}><X/></button></div><ProgressBar value={gt.length?pct(gd,gt.length):g.progress||0}/></Panel>}):<Empty title="Nessun obiettivo ancora" text="Inizia con una cosa concreta che vuoi migliorare." action="Crea obiettivo" onClick={()=>setOpen(true)}/>}</div>}
function Calendar({tasks,onToggle}){const [date,setDate]=useState(today());const dayTasks=tasks.filter(t=>t.task_date===date);const shift=n=>{const d=new Date(`${date}T12:00:00`);d.setDate(d.getDate()+n);setDate(d.toISOString().slice(0,10))};return <div className="page"><Header title="Calendario" subtitle="Il tuo percorso, giorno per giorno."/><Panel><div className="date-nav"><button className="icon" onClick={()=>shift(-1)}><ChevronLeft/></button><div><span className="eyebrow">GIORNO</span><h2>{fmt(date)}</h2></div><button className="icon" onClick={()=>shift(1)}><ChevronRight/></button><input type="date" value={date} onChange={e=>setDate(e.target.value)}/></div>{dayTasks.length?dayTasks.map(t=><button className="task-button" key={t.id} onClick={()=>onToggle(t.id,t.completed)}><span className={t.completed?'check done':'check'}>{t.completed&&<Check/>}</span><div><strong className={t.completed?'strike':''}>{t.title}</strong><small>{t.priority===1?'Alta priorità':'Azione del piano'}</small></div></button>):<p className="muted">Nessuna azione programmata.</p>}</Panel></div>}
function Focus({goals,uid}){const [minutes,setMinutes]=useState(25),[left,setLeft]=useState(25*60),[running,setRunning]=useState(false),[done,setDone]=useState(false);useEffect(()=>{setLeft(minutes*60)},[minutes]);useEffect(()=>{if(!running)return;const id=setInterval(()=>setLeft(x=>{if(x<=1){clearInterval(id);setRunning(false);setDone(true);return 0}return x-1}),1000);return()=>clearInterval(id)},[running]);const finish=async()=>{const actual=Math.max(0,Math.round((minutes*60-left)/60));await supabase.from('focus_sessions').insert({user_id:uid,goal_id:goals[0]?.id||null,planned_minutes:minutes,actual_minutes:actual,ended_at:new Date().toISOString()});setDone(false);setLeft(minutes*60)};return <div className="page"><Header title="Focus" subtitle="Una sessione. Una cosa importante."/><Panel><div className="focus"><div className="timer">{String(Math.floor(left/60)).padStart(2,'0')}:{String(left%60).padStart(2,'0')}</div><div className="focus-presets">{[15,25,45,60].map(m=><button className={minutes===m?'selected':''} onClick={()=>{setMinutes(m);setRunning(false)}} key={m}>{m} min</button>)}</div>{done?<><div className="msg ok">Sessione completata. Ottimo lavoro.</div><button className="primary" onClick={finish}>Salva sessione</button></>:<button className="primary" onClick={()=>setRunning(!running)}>{running?'Pausa':'Inizia focus'}<Zap/></button>}</div></Panel></div>}
function Progress({goals,tasks}){const completed=tasks.filter(t=>t.completed).length;const byDay=Array.from({length:7},(_,i)=>{const d=new Date();d.setDate(d.getDate()-6+i);const key=d.toISOString().slice(0,10);return {label:d.toLocaleDateString('it-IT',{weekday:'short'}),value:tasks.filter(t=>t.task_date===key&&t.completed).length}});return <div className="page"><Header title="Progressi" subtitle="Guarda la costanza, non solo il risultato."/><div className="metric-grid"><Metric icon={<Check/>} label="Task completati" value={completed}/><Metric icon={<Target/>} label="Obiettivi" value={goals.length}/><Metric icon={<Flame/>} label="Streak migliore" value={`${Math.max(...goals.map(g=>g.streak||0),0)} gg`}/><Metric icon={<Trophy/>} label="Percentuale" value={tasks.length?`${pct(completed,tasks.length)}%`:'0%'}/></div><Panel><div className="panel-head"><h2>Ultimi 7 giorni</h2><BarChart3/></div><div className="bars">{byDay.map(x=><div key={x.label}><div className="bar" style={{height:`${Math.max(8,Math.min(100,x.value*18))}%`}}/><span>{x.label}</span></div>)}</div></Panel><Panel><div className="panel-head"><h2>Come migliorare</h2><Activity/></div><p className="muted">Punta a completare almeno il 70% delle azioni programmate. La costanza batte la perfezione.</p></Panel></div>}
function Notifications({items,uid,reload}){const mark=async id=>{await supabase.from('notifications').update({read_at:new Date().toISOString()}).eq('id',id).eq('user_id',uid);reload()};return <div className="page"><Header title="Notifiche" subtitle="Le cose importanti, al momento giusto."/><Panel>{items.length?items.map(n=><button className={`notice ${n.read_at?'read':''}`} key={n.id} onClick={()=>mark(n.id)}><Bell/><div><strong>{n.title}</strong><p>{n.body}</p><small>{new Date(n.created_at).toLocaleString('it-IT')}</small></div></button>):<p className="muted">Non hai notifiche.</p>}</Panel></div>}
function Profile({profile,uid,onDone}){const [name,setName]=useState(profile.nickname),[saving,setSaving]=useState(false),[msg,setMsg]=useState('');const save=async()=>{setSaving(true);const {error}=await supabase.from('profiles').update({nickname:name.trim()}).eq('id',uid);setMsg(error?error.message:'Profilo aggiornato.');setSaving(false);if(!error)onDone()};const exportData=()=>{const data={profile,exported_at:new Date().toISOString()};const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));a.download='lifepilot-dati.json';a.click()};return <div className="page"><Header title="Profilo" subtitle="I tuoi dati, sotto il tuo controllo."/><Panel><label>Nickname<input value={name} onChange={e=>setName(e.target.value)}/></label>{msg&&<div className="msg ok">{msg}</div>}<div className="quick-row"><button className="primary" disabled={saving} onClick={save}>Salva modifiche<Check/></button><button onClick={exportData}>Esporta dati</button></div></Panel><Panel><div className="panel-head"><h2>LifePilot Pro</h2><Trophy/></div><p className="muted">AI planner, statistiche avanzate, focus e strumenti premium.</p><div className="pricing"><div><strong>€7,99</strong><span>/ mese</span></div><div><strong>€59,99</strong><span>/ anno</span></div></div><p className="muted small">Il checkout Stripe viene attivato quando il collegamento billing è configurato.</p></Panel></div>}
function TaskRow({task}){return <div className="task-row"><span className={task.completed?'check done':'check'}>{task.completed&&<Check/>}</span><div><strong className={task.completed?'strike':''}>{task.title}</strong><small>{task.task_date}</small></div></div>}
function Metric({icon,label,value}){return <div className="metric"><span>{icon}</span><div><small>{label}</small><strong>{value}</strong></div></div>}
function ProgressBar({value}){return <div className="progress"><i style={{width:`${Math.max(0,Math.min(100,Number(value)||0))}%`}}/></div>}
function Header({title,subtitle,action}){return <div className="page-head"><div><span className="eyebrow">LIFEPILOT</span><h1>{title}</h1><p>{subtitle}</p></div>{action}</div>}
function Panel({children}){return <section className="panel">{children}</section>}
function Empty({title,text,action,onClick}){return <Panel><div className="empty"><Sparkles/><h2>{title}</h2><p>{text}</p><button className="primary" onClick={onClick}>{action}<ArrowRight/></button></div></Panel>}
function Modal({title,close,children}){return <div className="modal-bg"><div className="modal"><div className="panel-head"><h2>{title}</h2><button className="icon" onClick={close}><X/></button></div>{children}</div></div>}
