import { supabase } from './lib/supabase';

let active = false;
const esc = v => String(v ?? '').replace(/[&<>'"]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function styles(){if(document.getElementById('lp-quiz-rewards-style'))return;const s=document.createElement('style');s.id='lp-quiz-rewards-style';s.textContent=`
.lp-quiz-backdrop{position:fixed;inset:0;z-index:12000;display:flex;align-items:center;justify-content:center;padding:16px;background:rgba(5,8,13,.72);backdrop-filter:blur(8px)}
.lp-quiz-card{width:min(520px,100%);background:var(--surface,#111722);color:var(--text,#fff);border:1px solid var(--border,#263242);border-radius:22px;padding:22px;box-shadow:0 30px 100px rgba(0,0,0,.45)}
.lp-quiz-card h2{margin:6px 0 8px}.lp-quiz-muted{color:var(--text-muted,#8b98a8);font-size:13px}.lp-quiz-options{display:grid;gap:10px;margin:18px 0}.lp-quiz-option{width:100%;text-align:left;padding:14px;border:1px solid var(--border,#263242);border-radius:13px;background:var(--surface-soft,#18202b);color:var(--text,#fff);font:inherit;font-weight:800;cursor:pointer}.lp-quiz-option:hover{border-color:var(--primary,#5eead4)}.lp-quiz-option.selected{border-color:var(--primary,#5eead4);box-shadow:0 0 0 2px color-mix(in srgb,var(--primary,#5eead4) 20%,transparent)}.lp-quiz-actions{display:flex;justify-content:flex-end;gap:8px}.lp-quiz-actions button{border:1px solid var(--border,#263242);border-radius:11px;padding:11px 15px;background:var(--surface-soft,#18202b);color:var(--text,#fff);font-weight:800}.lp-quiz-actions .primary{background:var(--primary,#5eead4);color:#071014;border-color:var(--primary,#5eead4)}
`;document.head.appendChild(s)}
async function quiz(sessionId){if(active)return;active=true;styles();const {data:q,error}=await supabase.rpc('get_life_session_quiz',{p_session_id:sessionId});if(error){active=false;alert(error.message);return}const options=Array.isArray(q?.options)?q.options:[];const root=document.createElement('div');root.className='lp-quiz-backdrop';root.innerHTML=`<div class="lp-quiz-card" role="dialog" aria-modal="true"><span class="eyebrow">QUIZ DI COMPLETAMENTO</span><h2>Dimostra di aver completato la sessione</h2><p>${esc(q.question)}</p><p class="lp-quiz-muted">Rispondi correttamente per ottenere i tuoi LifePoints e LifeCoins.</p><div class="lp-quiz-options">${options.map(o=>`<button class="lp-quiz-option" data-answer="${esc(o)}">${esc(o)} minuti</button>`).join('')}</div><div class="lp-quiz-actions"><button data-cancel>Annulla</button><button class="primary" data-submit disabled>Verifica</button></div><p class="lp-quiz-muted" data-status></p></div>`;document.body.appendChild(root);let answer='';const status=root.querySelector('[data-status]');const submit=root.querySelector('[data-submit]');root.querySelectorAll('[data-answer]').forEach(b=>b.addEventListener('click',()=>{root.querySelectorAll('[data-answer]').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');answer=b.dataset.answer;submit.disabled=false}));const close=()=>{root.remove();active=false};root.querySelector('[data-cancel]').onclick=close;submit.onclick=async()=>{submit.disabled=true;status.textContent='Verifica in corso…';const {data:r,error:e}=await supabase.rpc('submit_life_session_quiz',{p_session_id:sessionId,p_answer:answer});if(e){status.textContent=e.message;submit.disabled=false;return}if(!r?.passed){status.textContent='Risposta errata. Riprova.';submit.disabled=false;return}const {error:ce}=await supabase.rpc('complete_life_session',{p_session_id:sessionId});if(ce){status.textContent=ce.message;submit.disabled=false;return}status.textContent='✓ Corretto. Ricompensa assegnata.';setTimeout(()=>{close();window.dispatchEvent(new CustomEvent('lifepilot:gameplay-refresh'));},700)}}
function start(){styles();document.addEventListener('click',e=>{const b=e.target.closest?.('[data-complete]');if(!b)return;e.preventDefault();e.stopImmediatePropagation();quiz(b.dataset.complete)},true)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else start();
